### PR TITLE
Improvements documentation-archive-prepare script

### PR DESCRIPTION
**Pull request by SvMak**
The documentation-archive-prepare script can be run multiple times without creating duplicates.

REQUIRE MERGE PR: https://github.com/jhipster/documentation-archive/pull/154

Related to: https://github.com/jhipster/generator-jhipster/issues/27770

### CODE REVIEW

**Comment by SvMak** [comment]
@mraible Could you please check it?

And create new repo with name documentation-archive-v6-to-v7 for splitting current documentation archive?

**Comment by mraible** [comment]
I created a new repo at https://github.com/jhipster/documentation-archive-v6-to-v7.

**Comment by SvMak** [comment]
> I created a new repo at https://github.com/jhipster/documentation-archive-v6-to-v7.

Thanks a lot!

**Comment by SvMak** [comment]
> I created a new repo at https://github.com/jhipster/documentation-archive-v6-to-v7.

@mraible Could you please add some dummy README so I can fork it?

**Comment by mraible** [comment]
@SvMak Done.

**Comment by SvMak** [comment]
> @SvMak Done.

Thanks a lot! You are the best!

**Review by mraible — APPROVED** [review]

**Pull request merged**
